=== hurbeana/SSD/UE1/system.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="slotType">
    <xs:sequence >
      <xs:element name="input" type="inputoutputType" minOccurs="0"  maxOccurs="unbounded"/>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element name="slot" type="slotType"/>
        <xs:element name="ref">
          <xs:complexType>
            <xs:attribute name="id" type="xs:integer" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="conveyor" type="machines"/>
        <xs:element name="generator" type="machines"/>
        <xs:element name="machine" type="machines"/>
        <xs:element name="turntable" type="machines"/>
      </xs:choice>
      <xs:element name="output" type="inputoutputType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:integer" use="required"/>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="parallel" type="xs:boolean" default="false"/>
  </xs:complexType>

  <xs:complexType name="inputoutputType">
    <xs:sequence maxOccurs="unbounded">
      <xs:element name="item">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:integer">
              <xs:attribute name="id" type="xs:integer" use="required"/>
              <xs:attribute name="store" type="xs:integer"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="machines">
    <xs:all>
      <xs:element name="cost"/>
      <xs:element name="time"/>
    </xs:all>
    <xs:attribute name="name"/>
  </xs:complexType>

  <xs:element name="system">
    <xs:complexType>
      <xs:sequence minOccurs="0">
        <xs:element name="items" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="item" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" type="xs:integer" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="stores" maxOccurs="1">
          <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
              <xs:element name="store">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="type">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="normal"/>
                          <xs:enumeration value="waste"/>
                          <xs:enumeration value="sent"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="capacity" type="xs:integer"/>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:integer" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="area" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
              <xs:element name="slot" type="slotType"/>
            </xs:sequence>
            <xs:attribute name="name"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:key name="itemKeys">
      <xs:selector xpath="items/item"/>
      <xs:field xpath="@id"/>
    </xs:key>

    <xs:key name="storeKeys">
      <xs:selector xpath="stores/store"/>
      <xs:field xpath="@id"/>
    </xs:key>

    <xs:key name="slotKeys">
      <xs:selector xpath="area/slot"/>
      <xs:field xpath="@id"/>
    </xs:key>

    <xs:keyref name="slotKeysRef" refer="slotKeys">
      <xs:selector xpath="area/slot/ref"/>
      <xs:field xpath="@id"/>
    </xs:keyref>

    <xs:keyref name="inputitemKeyRef" refer="itemKeys">
      <xs:selector xpath="area/slot/input/item"/>
      <xs:field xpath="@id"/>
    </xs:keyref>
    
    <xs:keyref name="outputitemKeyRef" refer="itemKeys">
      <xs:selector xpath="area/slot/output/item"/>
      <xs:field xpath="@id"/>
    </xs:keyref>

    <xs:keyref name="inputstoreKeyRef" refer="slotKeys">
      <xs:selector xpath="area/slot/store/item"/>
      <xs:field xpath="@store"/>
    </xs:keyref>
    
    <xs:keyref name="outputstoreKeyRef" refer="slotKeys">
      <xs:selector xpath="area/slot/store/item"/>
      <xs:field xpath="@store"/>
    </xs:keyref>

    <xs:unique name="uniqueName">
      <xs:selector xpath=".//*"/>
      <xs:field xpath="@name"/>
    </xs:unique>
  </xs:element>
</xs:schema>

=== hurbeana/SSD/UE1/system-xsd.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<system xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="system.xsd">
  
  <items>
    <item id="1">item1</item>
    <item id="2">item2</item>
    <item id="3">item3</item>
    <item id="4">item4</item>
    <item id="5">item5</item>
  </items>

  <stores>
    <store id="1">
      <name>store1</name>
      <type>normal</type>
      <capacity>5</capacity>
    </store>
    <store id="2">
      <name>store2</name>
      <type>waste</type>
      <capacity>8</capacity>
    </store>
    <store id="3">
      <name>store3</name>
      <type>sent</type>
      <capacity>10</capacity>
    </store>
  </stores>

  <area name="area1">
    <slot id="1" name="slot1" parallel="true">
      <input>
        <item id="1" store="1">1</item>
        <item id="2" store="1">1</item>
      </input>
      <conveyor name="conveyor1">
        <cost>5</cost>
        <time>2</time>
      </conveyor>
      <output>
        <item id="3" store="1">1</item>
        <item id="4" store="1">1</item>
      </output>
    </slot>

    <slot id="2" name="slot2">
      <generator name="gen1">
        <cost>2</cost>
        <time>3</time>
      </generator>
      <ref id="1"/>
      <slot id="2" name="slot3">
        <input>
          <item id="5" store="2">5</item>
        </input>
        <ref id="1"/>
        <ref id="2"/>
      </slot>
      <output>
        <item id="3" store="2">2</item>
        <item id="4" store="2">2</item>
      </output>
    </slot>
  </area>
  <area name="area2">
    <slot id="4" name="slot4" parallel="true">
      <conveyor name="someotherconveyor">
        <cost>5</cost>
        <time>2</time>
      </conveyor>
      <slot id="5" name="slot5">
        <generator name="gen2">
          <cost>2</cost>
          <time>3</time>
        </generator>
        <ref id="1"/>
        <slot id="6" name="slot6">
          <ref id="2"/>
        </slot>
        <output>
          <item id="3" store="2">2</item>
          <item id="4" store="2">2</item>
        </output>
      </slot>
    </slot>

    
  </area>
</system>
